<footer>
    <nav>
        <ul>
            <li></li>
            <li>
                <a class="sprite social facebook" href="https://www.facebook.com/buyabrick" target="_blank">Facebook</a>
                <a class="sprite social twitter" href="http://twitter.com/weareteamafrica" target="_blank">Twitter</a>
                <a class="sprite social youtube" href="http://www.youtube.com/user/BuyaBrickFoundation1" target="_blank">YouTube</a>
            </li>
        </ul>
    </nav>
    <p class="copy">&copy; Buy a Brick Foundation</p>
</footer>