    <nav>
        <ul>
            <li><a href="/sub/subpage1.html">Projects</a>
                <ul>
                    <li><a href="/sub/subpage1.html">Current</a></li>
                    <li><a href="/sub/subpage1.html">Finished</a></li>
                    <li><a href="/sub/subpage1.html">Future</a></li>
                </ul>
            </li>
            <li><a href="/sub/subpage1.html">Get Involved</a>
                <ul>
                    <li><a href="/sub/subpage1.html">Pray</a></li>
                    <li><a href="/sub/subpage1.html">Donate</a></li>
                    <li><a href="/sub/subpage1.html">Volunteer</a></li>
                    <li><a href="/sub/subpage1.html">Partner</a></li>
                </ul>
            </li>
            <li class="no-sub"><a href="/sub/subpage1.html">Track Your Brick</a></li>
            <li><a href="/sub/subpage1.html">About Us</a>
                <ul>
                    <li><a href="/sub/subpage1.html">Mission</a></li>
                    <li><a href="/sub/subpage1.html">History</a></li>
                    <li><a href="/sub/subpage1.html">Team</a></li>
                    <li><a href="/sub/subpage1.html">Endorsements</a></li>
                </ul>
            </li>
            <li class="no-sub"><a href="/sub/subpage1.html">Contact</a></li>
        </ul>
    </nav>